<?php

/**
 * @file
 * The Social profile privacy module file.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function social_profile_privacy_form_social_profile_admin_settings_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#submit'][] = 'social_profile_privacy_admin_settings_form_submit';
}

/**
 * The submit function for social_profile_admin_settings_form().
 *
 * To save configuration of fields groups available to hiding.
 */
function social_profile_privacy_admin_settings_form_submit($form, FormStateInterface $form_state) {
  $config = \Drupal::configFactory()->getEditable('social_profile_privacy.settings');
  $config->set('limit_search_and_mention', $form_state->getValue('limit_search_and_mention'));

  $fields = $form_state->getValue('fields');

  $config->set('disclaimer', $fields['disclaimer']);

  unset($fields['disclaimer'], $fields['list']);

  // An array with fields, visibility settings that have been changed.
  $updated_fields = [];

  foreach ($fields as $field => $state) {
    if ($state !== '') {
      // Check if field settings have been changed.
      $current_value = $config->get('fields.' . $field);
      if (is_null($current_value) || ((int) $current_value !== (int) $state)) {
        $updated_fields[] = $field;
      }

      $config->set('fields.' . $field, $state);
    }
  }

  $config->save();
}

/**
 * Implements hook_social_user_name_display_suggestions_alter().
 *
 * Given that we're being extra strict about real names.
 * When there is both a full name and a nickname then we combine the two for
 * users that are allowed to see a full name even when there's a nickname.
 */
function social_profile_privacy_social_user_name_display_suggestions_alter(array &$suggestions, AccountInterface $account) {
  $config = \Drupal::config('social_profile_privacy.settings');

  if (
    $config->get('limit_search_and_mention')
    && isset($suggestions['full_name'], $suggestions['nickname'])
    && \Drupal::currentUser()->hasPermission('social profile privacy always show full name')
  ) {
    $suggestions['nickname_with_full_name'] = [
      'weight' => -PHP_INT_MAX,
      'name' => $suggestions['nickname']['name'] . ' (' . $suggestions['full_name']['name'] . ')',
    ];
  }
}
